apiVersion: v1
kind: Pod
metadata:
  namespace: devops-tools
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: gradle
      image: gradle:jdk17
      command:
        - cat
      tty: true
      volumeMounts:
        - name: jenkins-agent-data
          mountPath: /var/gradle_home
      env:
        - name: GRADLE_OPTS
          value: -Xmx1024m
    - name: docker
      image: docker:cli
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    - name: k8s-tools
      image: alpine/k8s:1.23.17
      command:
        - cat
      tty: true
    - name: npm
      image: node:lts-alpine3.17
      command:
        - cat
      tty: true
  volumes:
    - name: jenkins-agent-data
      persistentVolumeClaim:
        claimName: jenkins-agent-pvc
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
