version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=finance
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  grafana:
    image: finance-tool-grafana
    restart: always
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
    extra_hosts:
      - "host.docker.internal:host-gateway"
  finance-tool:
    image: finance-tool
    restart: always
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/finance"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '8080:8080'
volumes:
  db:
    driver: local
