---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: finance-tool-pvc
  namespace: finance-tool
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: finance-tool-pv
  namespace: finance-tool
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: finance-tool-pvc
    namespace: finance-tool
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/finance_tool_volume
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-node-1
