IF NOT EXISTS (
	SELECT * 
	FROM INFORMATION_SCHEMA.TABLES T 
		WHERE T.TABLE_NAME = 'categories'
		AND T.TABLE_SCHEMA = 'dbo')
BEGIN
	CREATE TABLE dbo.categories (
		id INT PRIMARY KEY IDENTITY(1,1),
		name VARCHAR(100),
		description VARCHAR(500)
	)
END
