name: Build and Publish
on: push

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        run: |
          ./gradlew build -i --build-cache --no-daemon
          sh 'ls ./build/libs -All'
          sh 'rm ./build/libs/*plain.jar'

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: docker build 'finance-tool:0.0.6-SNAPSHOT'

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: finance-tool:0.0.6-SNAPSHOT
          path: ./build/libs/*