name: Build and Publish
on: push

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Gradle Build
        run: |
          ./gradlew build -i --build-cache --no-daemon
          sh 'ls ./build/libs -All'
          sh 'rm ./build/libs/*plain.jar'
      - name: Docker Build
        run: docker build 'finance-tool:0.0.6-SNAPSHOT'
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: finance-tool:0.0.6-SNAPSHOT
          path: ./build/libs/*