name: Build and Publish

jobs:
  gradle-build:
    runs-on: gradle:jdk17
    steps:
      - name: Gradle Build
        run: |
          ./gradlew build -i --build-cache --no-daemon
          sh 'ls ./build/libs -All'
          sh 'rm ./build/libs/*plain.jar'

  docker-build:
    runs-on: docker:cli
    steps:
      - name: Docker Build
        run: docker build 'finance-tool:0.0.6-SNAPSHOT'

  publish:
    runs-on: ubuntu:latest
    steps:
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: finance-tool:0.0.6-SNAPSHOT
          path: ./build/libs/*